name: bio
channels:
  - defaults
dependencies:
  - glib-tools==2.78.4=h6a678d5_0
  - soupsieve==2.5=py312h06a4308_0
  - pysocks==1.7.1=py312h06a4308_0
  - charset-normalizer==3.3.2=pyhd3eb1b0_0
  - jupyterlab_widgets==3.0.10=py312h06a4308_0
  - openssl
  - rfc3339-validator==0.1.4=py312h06a4308_0
  - dbus==1.13.18=hb2f20db_0
  - send2trash==1.8.2=py312h06a4308_0
  - overrides==7.4.0=py312h06a4308_0
  - jupyter_client==8.6.0=py312h06a4308_0
  - nest-asyncio==1.6.0=py312h06a4308_0
  - platformdirs==3.10.0=py312h06a4308_0
  - wheel==0.44.0=py312h06a4308_0
  - parso==0.8.3=pyhd3eb1b0_0
  - lz4-c==1.9.4=h6a678d5_1
  - ply==3.11=py312h06a4308_1
  - setuptools==75.1.0=py312h06a4308_0
  - ipython==8.27.0=py312h06a4308_0
  - qt-main==5.15.2=h53bd1ea_10
  - defusedxml==0.7.1=pyhd3eb1b0_0
  - beautifulsoup4==4.12.3=py312h06a4308_0
  - pycparser==2.21=pyhd3eb1b0_0
  - pandocfilters==1.5.0=pyhd3eb1b0_0
  - sniffio==1.3.0=py312h06a4308_0
  - jupyterlab_server
  - argon2-cffi==21.3.0=pyhd3eb1b0_0
  - tk==8.6.14=h39e8969_0
  - pip==24.2=py312h06a4308_0
  - brotli-python==1.0.9=py312h6a678d5_8
  - fontconfig==2.14.1=h55d465d_3
  - tornado==6.4.1=py312h5eee18b_0
  - prompt_toolkit==3.0.43=hd3eb1b0_0
  - libgomp==11.2.0=h1234567_1
  - libcups==2.4.2=h2d74bed_1
  - glib==2.78.4=h6a678d5_0
  - attrs==23.1.0=py312h06a4308_0
  - ca-certificates
  - yaml==0.2.5=h7b6447c_0
  - gst-plugins-base==1.14.1=h6a678d5_1
  - jupyter_console
  - jupyterlab_pygments==0.1.2=py_0
  - icu==73.1=h6a678d5_0
  - six==1.16.0=pyhd3eb1b0_1
  - expat==2.6.3=h6a678d5_0
  - jupyter_core==5.7.2=py312h06a4308_0
  - decorator==5.1.1=pyhd3eb1b0_0
  - pcre2==10.42=hebb0a14_1
  - prometheus_client==0.14.1=py312h06a4308_0
  - zstd==1.5.5=hc292b87_2
  - pyzmq==25.1.2=py312h6a678d5_0
  - markupsafe==2.1.3=py312h5eee18b_0
  - tinycss2==1.2.1=py312h06a4308_0
  - libxkbcommon==1.0.1=h097e994_2
  - pygments==2.15.1=py312h06a4308_1
  - pure_eval==0.2.2=pyhd3eb1b0_0
  - jupyter_events==0.10.0=py312h06a4308_0
  - async-lru==2.0.4=py312h06a4308_0
  - zlib==1.2.13=h5eee18b_1
  - typing-extensions==4.11.0=py312h06a4308_0
  - nbclient==0.8.0=py312h06a4308_0
  - jsonschema-specifications==2023.7.1=py312h06a4308_0
  - referencing==0.30.2=py312h06a4308_0
  - python-fastjsonschema==2.16.2=py312h06a4308_0
  - stack_data==0.2.0=pyhd3eb1b0_0
  - psutil==5.9.0=py312h5eee18b_0
  - wcwidth==0.2.5=pyhd3eb1b0_0
  - jupyterlab
  - sqlite==3.45.3=h5eee18b_0
  - jupyter_server_terminals==0.4.4=py312h06a4308_1
  - cyrus-sasl==2.1.28=h52b45da_1
  - debugpy==1.6.7=py312h6a678d5_0
  - anyio==4.2.0=py312h06a4308_0
  - httpcore==1.0.2=py312h06a4308_0
  - krb5==1.20.1=h143b758_1
  - libllvm14==14.0.6=hecde1de_4
  - xz==5.4.6=h5eee18b_1
  - gstreamer==1.14.1=h5eee18b_1
  - libiconv==1.16=h5eee18b_3
  - libsodium==1.0.18=h7b6447c_0
  - python-dateutil==2.9.0post0=py312h06a4308_2
  - idna==3.7=py312h06a4308_0
  - jedi==0.19.1=py312h06a4308_0
  - notebook
  - pyyaml==6.0.1=py312h5eee18b_0
  - mysql==5.7.24=h721c034_2
  - _libgcc_mutex==0.1=main
  - pexpect==4.8.0=pyhd3eb1b0_3
  - terminado==0.17.1=py312h06a4308_0
  - executing==0.8.3=pyhd3eb1b0_0
  - zeromq==4.3.5=h6a678d5_0
  - typing_extensions==4.11.0=py312h06a4308_0
  - jupyter-lsp
  - notebook-shim
  - qtconsole
  - requests==2.32.3=py312h06a4308_0
  - certifi
  - nbconvert
  - sip
  - packaging==24.1=py312h06a4308_0
  - babel==2.11.0=py312h06a4308_0
  - libpng==1.6.39=h5eee18b_0
  - prompt-toolkit==3.0.43=py312h06a4308_0
  - h11==0.14.0=py312h06a4308_0
  - cffi==1.17.1=py312h1fdaa30_0
  - jsonschema==4.19.2=py312h06a4308_0
  - widgetsnbextension==4.0.10=py312h06a4308_0
  - libgcc-ng==11.2.0=h1234567_1
  - python-json-logger==2.0.7=py312h06a4308_0
  - libuuid==1.41.5=h5eee18b_0
  - ptyprocess==0.7.0=pyhd3eb1b0_2
  - traitlets==5.14.3=py312h06a4308_0
  - libclang==14.0.6=default_hc6dbbc7_1
  - libclang13==14.0.6=default_he11475f_1
  - libffi==3.4.4=h6a678d5_1
  - libxcb==1.15=h7f8727e_0
  - jupyter
  - pyqt
  - matplotlib-inline==0.1.6=py312h06a4308_0
  - bzip2==1.0.8=h5eee18b_6
  - httpx==0.27.0=py312h06a4308_0
  - ipywidgets==8.1.2=py312h06a4308_0
  - ncurses==6.4=h6a678d5_0
  - webencodings==0.5.1=py312h06a4308_2
  - jupyter_server
  - jpeg==9e=h5eee18b_3
  - ld_impl_linux-64==2.40=h12ee557_0
  - libglib==2.78.4=hdc74915_0
  - mistune==2.0.4=py312h06a4308_0
  - qtpy
  - libedit==3.1.20230828=h5eee18b_0
  - bleach
  - pyqt5-sip==12.13.0=py312h5eee18b_0
  - comm==0.2.1=py312h06a4308_0
  - rfc3986-validator==0.1.1=py312h06a4308_0
  - readline==8.2=h5eee18b_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - python==3.12.6=h5148396_1
  - libpq==12.17=hdbd6064_0
  - freetype==2.12.1=h4a9f257_0
  - nbformat==5.9.2=py312h06a4308_0
  - jinja2==3.1.4=py312h06a4308_0
  - asttokens==2.0.5=pyhd3eb1b0_0
  - libxml2==2.13.1=hfdd30dd_2
  - json5==0.9.6=pyhd3eb1b0_0
  - pytz==2024.1=py312h06a4308_0
  - rpds-py==0.10.6=py312hb02cf49_0
  - argon2-cffi-bindings==21.2.0=py312h5eee18b_0
  - _openmp_mutex==5.1=1_gnu
  - websocket-client==1.8.0=py312h06a4308_0
  - ipykernel
  - torchvision
  - pytorch-cuda=12.1
  - torchaudio
  - pytorch
prefix: /local_home/wuqitian/anaconda3/envs/bio